[build-system]
requires = [
    "setuptools>=61",
    "wheel",
]
build-backend = "setuptools.build_meta"


[project]
name = "enkard"
version = "0.1.3"
description = "Card generator and fetching basic data for Genshin Impact"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "Breeze" }
]

dependencies = [
    "aiofiles",
    "aiohttp",
    "aiosqlite",
    "asyncache",
    "cachetools",
    "loguru",
    "orjson",
    "Pillow",
    "pydantic",
    "curl_cffi"
]


[tool.setuptools.packages.find]
include = [
    "enkard*",
]


[tool.setuptools.package-data]
"enkard.enkacard" = [
    "assets/**/*.png",
    "assets/**/*.ttf",
]